const COUNTRIES = [
  { value: 'CN', label: 'China (UTC+8)' },
  { value: 'US', label: 'United States (UTC−5 to UTC−10)' },
  { value: 'GB', label: 'United Kingdom (UTC+0/UTC+1)' },
  { value: 'CA', label: 'Canada (UTC−3.5 to UTC−8)' },
  { value: 'AU', label: 'Australia (UTC+8 to UTC+11)' },
  { value: 'JP', label: 'Japan (UTC+9)' },
  { value: 'DE', label: 'Germany (UTC+1/UTC+2)' },
  { value: 'FR', label: 'France (UTC+1/UTC+2)' },
  { value: 'ES', label: 'Spain (UTC+1/UTC+2)' },
  { value: 'SG', label: 'Singapore (UTC+8)' },
  { value: 'KR', label: 'Korea, Republic of (UTC+9)' },
  { value: 'AF', label: 'Afghanistan (UTC+4:30)' },
  { value: 'AL', label: 'Albania (UTC+1/UTC+2)' },
  { value: 'DZ', label: 'Algeria (UTC+1)' },
  { value: 'AD', label: 'Andorra (UTC+1/UTC+2)' },
  { value: 'AO', label: 'Angola (UTC+1)' },
  { value: 'AR', label: 'Argentina (UTC−3)' },
  { value: 'AM', label: 'Armenia (UTC+4)' },
  { value: 'AT', label: 'Austria (UTC+1/UTC+2)' },
  { value: 'BH', label: 'Bahrain (UTC+3)' },
  { value: 'BD', label: 'Bangladesh (UTC+6)' },
  { value: 'BY', label: 'Belarus (UTC+3)' },
  { value: 'BE', label: 'Belgium (UTC+1/UTC+2)' },
  { value: 'BR', label: 'Brazil (UTC−2 to UTC−5)' },
  { value: 'BG', label: 'Bulgaria (UTC+2/UTC+3)' },
  { value: 'CL', label: 'Chile (UTC−3/UTC−4)' },
  { value: 'CO', label: 'Colombia (UTC−5)' },
  { value: 'CR', label: 'Costa Rica (UTC−6)' },
  { value: 'HR', label: 'Croatia (UTC+1/UTC+2)' },
  { value: 'CU', label: 'Cuba (UTC−5/UTC−4)' },
  { value: 'CY', label: 'Cyprus (UTC+2/UTC+3)' },
  { value: 'CZ', label: 'Czechia (UTC+1/UTC+2)' },
  { value: 'DK', label: 'Denmark (UTC+1/UTC+2)' },
  { value: 'EG', label: 'Egypt (UTC+2)' },
  { value: 'EE', label: 'Estonia (UTC+2/UTC+3)' },
  { value: 'FI', label: 'Finland (UTC+2/UTC+3)' },
  { value: 'GR', label: 'Greece (UTC+2/UTC+3)' },
  { value: 'HK', label: 'Hong Kong (UTC+8)' },
  { value: 'HU', label: 'Hungary (UTC+1/UTC+2)' },
  { value: 'IS', label: 'Iceland (UTC+0)' },
  { value: 'IN', label: 'India (UTC+5:30)' },
  { value: 'ID', label: 'Indonesia (UTC+7 to UTC+9)' },
  { value: 'IE', label: 'Ireland (UTC+0/UTC+1)' },
  { value: 'IL', label: 'Israel (UTC+2/UTC+3)' },
  { value: 'IT', label: 'Italy (UTC+1/UTC+2)' },
  { value: 'KW', label: 'Kuwait (UTC+3)' },
  { value: 'MY', label: 'Malaysia (UTC+8)' },
  { value: 'MX', label: 'Mexico (UTC−5 to UTC−8)' },
  { value: 'MA', label: 'Morocco (UTC+0/UTC+1)' },
  { value: 'NP', label: 'Nepal (UTC+5:45)' },
  { value: 'NZ', label: 'New Zealand (UTC+12/UTC+13)' },
  { value: 'NG', label: 'Nigeria (UTC+1)' },
  { value: 'NO', label: 'Norway (UTC+1/UTC+2)' },
  { value: 'PK', label: 'Pakistan (UTC+5)' },
  { value: 'PE', label: 'Peru (UTC−5)' },
  { value: 'PH', label: 'Philippines (UTC+8)' },
  { value: 'PL', label: 'Poland (UTC+1/UTC+2)' },
  { value: 'PT', label: 'Portugal (UTC+0/UTC+1)' },
  { value: 'QA', label: 'Qatar (UTC+3)' },
  { value: 'RO', label: 'Romania (UTC+2/UTC+3)' },
  { value: 'RU', label: 'Russia (UTC+2 to UTC+12)' },
  { value: 'SA', label: 'Saudi Arabia (UTC+3)' },
  { value: 'ZA', label: 'South Africa (UTC+2)' },
  { value: 'SE', label: 'Sweden (UTC+1/UTC+2)' },
  { value: 'CH', label: 'Switzerland (UTC+1/UTC+2)' },
  { value: 'TW', label: 'Taiwan (UTC+8)' },
  { value: 'TH', label: 'Thailand (UTC+7)' },
  { value: 'TR', label: 'Turkey (UTC+3)' },
  { value: 'UA', label: 'Ukraine (UTC+2/UTC+3)' },
  { value: 'AE', label: 'United Arab Emirates (UTC+4)' },
  { value: 'VN', label: 'Vietnam (UTC+7)' },
];
window.COUNTRIES = COUNTRIES;